//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MereNear.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MereNear.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mere Near.
        /// </summary>
        public static string AboutMereNearLabel {
            get {
                return ResourceManager.GetString("AboutMereNearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUsMenu {
            get {
                return ResourceManager.GetString("AboutUsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountHeading {
            get {
                return ResourceManager.GetString("AccountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photos(optional).
        /// </summary>
        public static string AddPhotosLabel {
            get {
                return ResourceManager.GetString("AddPhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Jobs.
        /// </summary>
        public static string AllJobstitle {
            get {
                return ResourceManager.GetString("AllJobstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Notifications.
        /// </summary>
        public static string AppNotificationLabel {
            get {
                return ResourceManager.GetString("AppNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find services near you very easily.
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguageLabel {
            get {
                return ResourceManager.GetString("ChangeLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Mobile Number.
        /// </summary>
        public static string ChangeMobileNumberLabel {
            get {
                return ResourceManager.GetString("ChangeMobileNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Phone Number.
        /// </summary>
        public static string ChangeNumberTitle {
            get {
                return ResourceManager.GetString("ChangeNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure this number can receive SMS.
        /// </summary>
        public static string ChnageNumberSureLabel {
            get {
                return ResourceManager.GetString("ChnageNumberSureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category.
        /// </summary>
        public static string ChooseCategoryLabel {
            get {
                return ResourceManager.GetString("ChooseCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        public static string ChooseLocationLabel {
            get {
                return ResourceManager.GetString("ChooseLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Number.
        /// </summary>
        public static string CurrentNumberLabel {
            get {
                return ResourceManager.GetString("CurrentNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a deal about this job.
        /// </summary>
        public static string DealMessage {
            get {
                return ResourceManager.GetString("DealMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent a deal about this job.
        /// </summary>
        public static string DealMessageSender {
            get {
                return ResourceManager.GetString("DealMessageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string DealMessageTitle {
            get {
                return ResourceManager.GetString("DealMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase cost:.
        /// </summary>
        public static string DealPopupPurchase {
            get {
                return ResourceManager.GetString("DealPopupPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string DeclineButton {
            get {
                return ResourceManager.GetString("DeclineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string DescriptionEditorPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionEditorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsLabel {
            get {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string DistanceHeader {
            get {
                return ResourceManager.GetString("DistanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Location.
        /// </summary>
        public static string DropLocationLabel {
            get {
                return ResourceManager.GetString("DropLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        public static string ImmediatelyLabel {
            get {
                return ResourceManager.GetString("ImmediatelyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this is your phone number?.
        /// </summary>
        public static string IsThisPhoneNumberLabel {
            get {
                return ResourceManager.GetString("IsThisPhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescriptionLabel {
            get {
                return ResourceManager.GetString("JobDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string JobStatusActive {
            get {
                return ResourceManager.GetString("JobStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string JobStatusCompleted {
            get {
                return ResourceManager.GetString("JobStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        public static string JobStatusLabel {
            get {
                return ResourceManager.GetString("JobStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        public static string JobStatusProgress {
            get {
                return ResourceManager.GetString("JobStatusProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string jobTitleLabel {
            get {
                return ResourceManager.GetString("jobTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutMenu {
            get {
                return ResourceManager.GetString("LogoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a job.
        /// </summary>
        public static string LookingJob {
            get {
                return ResourceManager.GetString("LookingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a deal.
        /// </summary>
        public static string MakeDealButton {
            get {
                return ResourceManager.GetString("MakeDealButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MereNear.
        /// </summary>
        public static string MereNear {
            get {
                return ResourceManager.GetString("MereNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesTab {
            get {
                return ResourceManager.GetString("MessagesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your number.
        /// </summary>
        public static string MobileEntryPlaceholder {
            get {
                return ResourceManager.GetString("MobileEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile number to get started.
        /// </summary>
        public static string MobileEntryTitle {
            get {
                return ResourceManager.GetString("MobileEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MoreHeader {
            get {
                return ResourceManager.GetString("MoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Jobs.
        /// </summary>
        public static string MyJobsTab {
            get {
                return ResourceManager.GetString("MyJobsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Posts.
        /// </summary>
        public static string MyPostsMenu {
            get {
                return ResourceManager.GetString("MyPostsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Service.
        /// </summary>
        public static string NeedServiceLabel {
            get {
                return ResourceManager.GetString("NeedServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My new number is.
        /// </summary>
        public static string NewNumberLabel {
            get {
                return ResourceManager.GetString("NewNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationHeading {
            get {
                return ResourceManager.GetString("NotificationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationLabel {
            get {
                return ResourceManager.GetString("NotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsTab {
            get {
                return ResourceManager.GetString("NotificationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP you recieved.
        /// </summary>
        public static string OTPMainLabel {
            get {
                return ResourceManager.GetString("OTPMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Policies.
        /// </summary>
        public static string OurPoliciesMenu {
            get {
                return ResourceManager.GetString("OurPoliciesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotosLabel {
            get {
                return ResourceManager.GetString("PhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send me the deal.
        /// </summary>
        public static string PleaseSendDealButton {
            get {
                return ResourceManager.GetString("PleaseSendDealButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted On.
        /// </summary>
        public static string PostedOn {
            get {
                return ResourceManager.GetString("PostedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a job.
        /// </summary>
        public static string PostJob {
            get {
                return ResourceManager.GetString("PostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewButton {
            get {
                return ResourceManager.GetString("PreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileTab {
            get {
                return ResourceManager.GetString("ProfileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter purchase amount.
        /// </summary>
        public static string PurchaseAmountEntry {
            get {
                return ResourceManager.GetString("PurchaseAmountEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Us.
        /// </summary>
        public static string RateUsMenu {
            get {
                return ResourceManager.GetString("RateUsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for report.
        /// </summary>
        public static string ReasonForReportLabel {
            get {
                return ResourceManager.GetString("ReasonForReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an SMS.
        /// </summary>
        public static string ReceiveSMS {
            get {
                return ResourceManager.GetString("ReceiveSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ReportButton {
            get {
                return ResourceManager.GetString("ReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your reason of reporting.
        /// </summary>
        public static string ResaonReportPlaceholder {
            get {
                return ResourceManager.GetString("ResaonReportPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review.
        /// </summary>
        public static string ReviewButton {
            get {
                return ResourceManager.GetString("ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment.
        /// </summary>
        public static string ReviewPopupEditor {
            get {
                return ResourceManager.GetString("ReviewPopupEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Rating.
        /// </summary>
        public static string ReviewPopupTitle {
            get {
                return ResourceManager.GetString("ReviewPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule your job.
        /// </summary>
        public static string ScheduleLabel {
            get {
                return ResourceManager.GetString("ScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charge:.
        /// </summary>
        public static string ServiceCharge {
            get {
                return ResourceManager.GetString("ServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter service charge.
        /// </summary>
        public static string ServiceChargeEntry {
            get {
                return ResourceManager.GetString("ServiceChargeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Location.
        /// </summary>
        public static string ShareLocationButton {
            get {
                return ResourceManager.GetString("ShareLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total:.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportMenu {
            get {
                return ResourceManager.GetString("SupportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message...
        /// </summary>
        public static string TypeMessagePlaceholder {
            get {
                return ResourceManager.GetString("TypeMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your New Number.
        /// </summary>
        public static string VerifyNumberTitle {
            get {
                return ResourceManager.GetString("VerifyNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
